# -*- coding: utf-8 -*-
"""Step15_복잡한_계산_그래프(이론_편).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9FJmqqXGnKAtecUFX1BOvQL1PG_tXnS

#Step15 복잡한 계산 그래프(이론 편)
##15.1 역전파의 올바른 순서
현재의 구현으로는 복잡한 계산 그래프를 제대로 처리할 수 없음
-> 역전파시, gradient가 계산되는 순서가 직선적임.
-> gradient가 계산되는 순서를 explicit하게 표시해줄 방안이 필요
-> '세대'를 나눠보자
"""

